function formatEquationForCPP(coeff)
    eq = sprintf(['(%d)+(%d)*X+(%d)*Y\n', ...
    '+(%d)*pow(X,2)+(%d)*X*Y+(%d)*pow(Y,2)\n', ...
    '+(%d)*pow(X,3)+(%d)*pow(X,2)*Y+(%d)*Xpow(Y,2)+(%d)*pow(Y,3)\n', ...
    '+(%d)*pow(X,4)+(%d)*pow(X,3)*Y+(%d)*pow(X,2)*pow(Y,2)\n', ...
    '+(%d)*X*pow(Y,3)+(%d)*pow(Y,4)\n', ...
    '+(%d)*pow(X,5)+(%d)*pow(X,4)*Y+(%d)*pow(X,3)*pow(Y,2)\n', ...
    '+(%d)*pow(X,2)*pow(Y,3)+(%d)*X*pow(Y,4)+(%d)*pow(Y,5)\n', ...
    '+(%d)*pow(X,6)+(%d)*pow(X,5)*Y+(%d)*pow(X,4)*pow(Y,2)\n', ...
    '+(%d)*pow(X,3)*pow(Y,3)+(%d)*pow(X,2)*pow(Y,4)\n', ...
    '+(%d)*X*pow(Y,5)+(%d)*pow(Y,6)\n', ...
    '+(%d)*pow(X,7)+(%d)*pow(X,6)*Y+(%d)*pow(X,5)*pow(Y,2)\n', ...
    '+(%d)*pow(X,4)*pow(Y,3)+(%d)*pow(X,3)*pow(Y,4)+(%d)*pow(X,2)*pow(Y,5)\n', ...
    '+(%d)*X*pow(Y,6)+(%d)*pow(Y,7)\n'], coeff);

    fileID = fopen('equation.txt','w');
    fprintf(fileID, eq);
    fclose(fileID);
end